### ISSUE TITLE
skin page template

### ISSUE THREAD

**Issue by Remian103** [Remian103/lolskin-price-tracker#16]
skins page template
working on branch 'frontend-skin-page'

### To-do
- [x] full skin image in background
- [x] timeline graph about skin price
- [x] another skins of its champion

**Comment by Remian103** [comment]
graph will be implemented by [Chart.js](https://www.chartjs.org/)
