### ISSUE TITLE
data fetching hook

### ISSUE THREAD

**Issue by Remian103** [Remian103/lolskin-price-tracker#17]
backend에서 데이터를 불러오는 custom hook추가 예정

frontend-data-fetch 브랜치에서 작업중

**Comment by Remian103** [comment]
reference site
https://www.robinwieruch.de/react-hooks-fetch-data

**Comment by Remian103** [comment]
### To-Do

- [ ] implement custom hook for data fetching

> apply to each component

- [ ] ChampBox - skin list about each champ
- [ ] ChampBox - champion list
- [ ] recommend-skins - skin list
